"""initial migration

Revision ID: f37b87860a45
Revises: 
Create Date: 2025-04-06 11:45:05.400907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f37b87860a45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diaper_changes',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('type', sa.Enum('PEE', 'POOP', 'BOTH',
                              name='diapertype'), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diaper_changes')
    # ### end Alembic commands ###
